# Generated by Django 5.2.1 on 2025-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'objeto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        #migrations.DeleteModel(
            #name='guzman_producto2',
        #),
    ]
